package paccor.tcg.credential;

import jakarta.validation.constraints.Size;
import java.util.Arrays;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Singular;
import org.bouncycastle.asn1.ASN1EncodableVector;
import org.bouncycastle.asn1.ASN1Object;
import org.bouncycastle.asn1.ASN1Primitive;
import org.bouncycastle.asn1.ASN1Sequence;
import org.bouncycastle.asn1.ASN1TaggedObject;
import org.bouncycastle.asn1.DERSequence;

/**
 * <pre>{@code
 * TCGRelevantCredentials::=
 *      SEQUENCE SIZE (1..REFMAX) OF HashedSubjectInfoURI
 * }</pre>
 */
@AllArgsConstructor
@Builder(toBuilder = true)
@EqualsAndHashCode(callSuper = false)
@Getter
@NoArgsConstructor(force = true)
public class TCGRelevantCredentials extends ASN1Object {

	@Singular
	@Size(min = 1, max = Definitions.REFMAX)
	private final List<HashedSubjectInfoURI> urls;

	/**
	 * Attempts to cast the provided object.
	 * If the object is an ASN1Sequence, the object is parsed by fromASN1Sequence.
	 * @param obj the object to parse
	 * @return {@link TCGRelevantCredentials}
	 */
	public static final TCGRelevantCredentials getInstance(Object obj) {
		if (obj == null || obj instanceof TCGRelevantCredentials) {
			return (TCGRelevantCredentials) obj;
		}
        if (obj instanceof ASN1Sequence || obj instanceof ASN1TaggedObject) {
            return fromASN1Sequence(ASN1Utils.getSequence(obj));
		}
		throw new IllegalArgumentException("Illegal argument in getInstance: " + obj.getClass().getName());
	}

	/**
	 * Attempts to parse the given ASN1Sequence.
	 * @param seq An ASN1Sequence
	 * @return {@link TCGRelevantCredentials}
	 */
	public static final TCGRelevantCredentials fromASN1Sequence(@NonNull ASN1Sequence seq) {
		TCGRelevantCredentials.TCGRelevantCredentialsBuilder builder = TCGRelevantCredentials.builder();
		builder.urlsFromSequence(seq);
		return builder.build();
	}

	/**
	 * @return This object as an ASN1Sequence
	 */
	public ASN1Primitive toASN1Primitive() {
		ASN1EncodableVector vec = new ASN1EncodableVector();
		if (urls != null) {
			vec.addAll(ASN1Utils.toASN1EncodableVector(urls));
		}
		return new DERSequence(vec);
	}

	/**
	 * The rest of this builder is generated by lombok Builder annotation
	 */
	public static class TCGRelevantCredentialsBuilder {
		/**
		 * Reads elements of the given sequence as HashedSubjectInfoURI and adds them to the builder.
		 * @param seq ASN1Sequence
		 */
		public final void urlsFromSequence(@NonNull ASN1Sequence seq) {
			Arrays.asList(seq.toArray()).forEach(
					element ->
							this.url(HashedSubjectInfoURI.getInstance(element)));
		}
	}
}
