<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>NSA Cybersecurity Directorate</Authors>
    <PackageId>paccor.HardwareManifestPluginManager</PackageId>
    <Description>Loads paccor hardware manifest plugins by name so a .NET program can collect component identifiers for TCG Platform Certificates.</Description>
    <PackageVersion>2.1.1</PackageVersion>
    <PackageTags>paccor;platform;certificate;hardware;manifest;plugin;manager</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <!--Source Link github.com/dotnet/sourcelink -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HardwareManifestPlugin\HardwareManifestPlugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!--Package resources -->
    <None Include="..\..\..\LICENSE.md" Pack="true" PackagePath="LICENSE.md" />
    <None Include="..\..\..\images\paccorpluginslogoicon.png" Pack="true" PackagePath="icon.png" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
