package tcg.credential;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonClassDescription;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import org.bouncycastle.asn1.ASN1EncodableVector;
import org.bouncycastle.asn1.ASN1Object;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.ASN1Primitive;
import org.bouncycastle.asn1.ASN1Sequence;
import org.bouncycastle.asn1.ASN1TaggedObject;
import org.bouncycastle.asn1.ASN1UTF8String;
import org.bouncycastle.asn1.DERSequence;

/**
 * <pre>{@code
 * ComponentAddress ::= SEQUENCE {
 *      addressType AddressType,
 *      addressValue UTF8String (SIZE (1..STRMAX)) }
 *
 * AddressType ::= OBJECT IDENTIFIER (tcg-address-ethernetmac | tcg-address-wlanmac | tcg-address-bluetoothmac)
 * }</pre>
 */
@AllArgsConstructor
@Builder(toBuilder = true)
@EqualsAndHashCode(callSuper = false)
@JsonClassDescription("Network or hardware address identified by an address-type OID and a UTF-8 address value.")
@JsonFormat(with = JsonFormat.Feature.ACCEPT_CASE_INSENSITIVE_PROPERTIES)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@NoArgsConstructor(force = true)
public class ComponentAddress extends ASN1Object {
	private static final int SEQUENCE_SIZE = 2;

	@JsonPropertyDescription("Address type OID. In shorthand JSON input, this is inferred from the single property name.")
	@NonNull
	@NotNull
	private final ASN1ObjectIdentifier addressType;
	@JsonPropertyDescription("Address value, such as a MAC address string.")
	@NonNull
	@NotNull
	private final ASN1UTF8String addressValue;

	/**
	 * Attempts to cast the provided object.
	 * If the object is an ASN1Sequence, the object is parsed by fromASN1Sequence.
	 * @param obj the object to parse
	 * @return ComponentAddress
	 */
	public static ComponentAddress getInstance(Object obj) {
		if (obj == null || obj instanceof ComponentAddress) {
			return (ComponentAddress) obj;
		}
        if (obj instanceof ASN1Sequence || obj instanceof ASN1TaggedObject) {
            return fromASN1Sequence(ASN1Utils.getSequence(obj));
		}
		throw new IllegalArgumentException("Illegal argument in getInstance: " + obj.getClass().getName());
	}

	/**
	 * Attempts to parse the given ASN1Sequence.
	 * @param seq An ASN1Sequence
	 * @return ComponentAddress
	 */
	public static final ComponentAddress fromASN1Sequence(@NonNull ASN1Sequence seq) {
		if (seq.size() != ComponentAddress.SEQUENCE_SIZE) {
			throw new IllegalArgumentException("Bad sequence size: " + seq.size());
		}

        List<ASN1Object> untaggedElements = ASN1Utils.listUntaggedElements(seq);

		ComponentAddress.ComponentAddressBuilder builder = ComponentAddress.builder()
				.addressType(ASN1ObjectIdentifier.getInstance(untaggedElements.get(0)))
				.addressValue(ASN1UTF8String.getInstance(untaggedElements.get(1)));

		return builder.build();
	}

	/**
	 * @return This object as an ASN1Sequence
	 */
	public ASN1Primitive toASN1Primitive() {
		ASN1EncodableVector vec = new ASN1EncodableVector();
		vec.add(addressType);
		vec.add(addressValue);
		return new DERSequence(vec);
	}

	/**
     * The rest of this builder is generated by lombok Builder annotation
     */
    public static class ComponentAddressBuilder {
		/**
		 * Sets the address type for the component using the provided enum value.
		 * @param type the address type
		 */
		public final void addressTypeFromEnum(@NonNull ComponentAddressType type) {
            this.addressType(type.getOid());
        }
	}
}
