package tcg.credential;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * <pre>
 * EKGenerationLocation ::= ENUMERATED {
 *      tpmManufacturer (0),
 *      platformManufacturer (1),
 *      ekCertSigner (2) }
 * </pre>
 */
public class EKGenerationLocation extends ASN1EnumeratedEnumBase<EKGenerationLocation.Enumerated> {
	/**
	 * Factory object used to provide conversion context.
	 */
	public static final Factory<Enumerated, EKGenerationLocation> FACTORY = factory(Enumerated.class, EKGenerationLocation::new);

	/**
	 * EKGenerationLocation options
	 */
	@AllArgsConstructor
	@Getter
	public enum Enumerated implements EnumWithIntegerValue {
		/**
		 * tpmManufacturer: EK generated by TPM manufacturer
		 */
		tpmManufacturer(0),
		/**
		 * platformManufacturer: EK generated by platform manufacturer
		 */
		platformManufacturer(1),
		/**
		 * ekCertSigner: EK generated by same entity as EK certificate signer
		 */
		ekCertSigner(2);

		private final int value;
	}

	/**
	 * Convert data into an EKGenerationLocation object.
	 * @param obj Could be any type that can be transformed into ASN1Enumerated
	 * @return EKGenerationLocation
	 */
	public static EKGenerationLocation getInstance(Object obj) {
		return ASN1EnumBase.getInstance(obj, FACTORY);
	}

	/**
	 * New EKGenerationLocation, looking up the given value in the enum class.
	 * @param value value to look up
	 */
	public EKGenerationLocation(int value) {
		super(value, Enumerated.class);
	}
}
