package tcg.credential;

import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Singular;
import org.bouncycastle.asn1.ASN1EncodableVector;
import org.bouncycastle.asn1.ASN1Object;
import org.bouncycastle.asn1.ASN1Primitive;
import org.bouncycastle.asn1.ASN1Sequence;
import org.bouncycastle.asn1.DERSequence;
import org.bouncycastle.asn1.DERTaggedObject;
import java.util.List;

/**
 * <pre>
 * platformConfiguration ATTRIBUTE ::= {
 *      WITH SYNTAX PlatformConfiguration
 *      ID tcg-at-platformConfiguration-v1 }
 *
 * PlatformConfiguration ::= SEQUENCE {
 *      componentIdentifier [0] IMPLICIT SEQUENCE(SIZE(1..CONFIGMAX)) OF ComponentIdentifier OPTIONAL,
 *      platformProperties [1] IMPLICIT SEQUENCE(SIZE(1..CONFIGMAX)) OF Properties OPTIONAL,
 *      platformPropertiesUri [2] IMPLICIT URIReference OPTIONAL }
 * </pre>
 */
@AllArgsConstructor
@Builder(toBuilder = true)
@Getter
@NoArgsConstructor(force = true)
public class PlatformConfiguration extends ASN1Object {
	private static final int MIN_SEQUENCE_SIZE = 0;
	private static final int MAX_SEQUENCE_SIZE = 3;

	@Singular
	private final List<ComponentIdentifier> componentIdentifiers; // optional, tagged 0
	@Singular
	private final List<PlatformProperties> platformProperties; // optional, tagged 1
	private final URIReference platformPropertiesUri; // optional, tagged 2

	/**
	 * Attempts to cast the provided object.
	 * If the object is an ASN1Sequence, the object is parsed by fromASN1Sequence.
	 * @param obj the object to parse
	 * @return PlatformConfiguration
	 */
	public static PlatformConfiguration getInstance(Object obj) {
		if (obj == null || obj instanceof PlatformConfiguration) {
			return (PlatformConfiguration) obj;
		}
		if (obj instanceof ASN1Sequence seq) {
			return PlatformConfiguration.fromASN1Sequence(seq);
		}
		throw new IllegalArgumentException("Illegal argument in getInstance: " + obj.getClass().getName());
	}

	/**
	 * Attempts to parse the given ASN1Sequence.
	 * @param seq An ASN1Sequence
	 * @return PlatformConfiguration
	 */
	public static PlatformConfiguration fromASN1Sequence(@NonNull ASN1Sequence seq) {
		if (seq.size() < PlatformConfiguration.MIN_SEQUENCE_SIZE) {
			throw new IllegalArgumentException("Bad sequence size: " + seq.size());
		}

		PlatformConfiguration.PlatformConfigurationBuilder builder = PlatformConfiguration.builder();

		ASN1Utils.parseTaggedElements(seq).forEach((key, value) -> {
			switch (key) {
				case 0 -> builder.componentIdentifiersFromSequence(ASN1Sequence.getInstance(value));
				case 1 -> builder.platformPropertiesFromSequence(ASN1Sequence.getInstance(value));
				case 2 -> builder.platformPropertiesUri(URIReference.getInstance(value));
				default -> {}
			}
		});

		return builder.build();
	}

	/**
	 * @return This object as an ASN1Sequence
	 */
	public ASN1Primitive toASN1Primitive() {
		ASN1EncodableVector vec = new ASN1EncodableVector();
		if (componentIdentifiers != null) {
			vec.add(new DERTaggedObject(false, 0, new DERSequence(ASN1Utils.toASN1EncodableVector(componentIdentifiers))));
		}
		if (platformProperties != null) {
			vec.add(new DERTaggedObject(false, 1, new DERSequence(ASN1Utils.toASN1EncodableVector(platformProperties))));
		}
		if (platformPropertiesUri != null) {
			vec.add(new DERTaggedObject(false, 2, platformPropertiesUri));
		}
		return new DERSequence(vec);
	}

	/**
	 * The rest of this builder is generated by lombok Builder annotation
	 */
	public static class PlatformConfigurationBuilder {
		/**
		 * Reads elements of the given sequence as ComponentIdentifiers and adds them to the builder.
		 * @param seq ASN1Sequence
		 */
		public final void componentIdentifiersFromSequence(@NonNull ASN1Sequence seq) {
			Arrays.asList(seq.toArray()).forEach(
					element ->
							this.componentIdentifier(ComponentIdentifier.getInstance(element)));
		}

		/**
		 * Reads elements of the given sequence as PlatformProperties and adds them to the builder.
		 * @param seq ASN1Sequence
		 */
		public final void platformPropertiesFromSequence(@NonNull ASN1Sequence seq) {
			Arrays.asList(seq.toArray()).forEach(
					element ->
							this.platformProperty(PlatformProperties.getInstance(element)));
		}
	}
}
