<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <Authors>NSA Cybersecurity Directorate</Authors>
    <PackageId>paccor.paccor_scripts</PackageId>
    <PackageVersion>2.6.0</PackageVersion>
    <PackageTags>paccor;platform;certificate;hardware;manifest;scripts;component;class;registry;evidence;collection</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <!--Source Link github.com/dotnet/sourcelink -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);NU5110,NU5111</NoWarn> <!--Warnings related to inclusion of scripts managed outside this project.-->
  </PropertyGroup>

  <Target Name="CopyFiles" BeforeTargets="PreBuildEvent">
    <ItemGroup>
      <PaccorScriptsLinux Include="..\..\..\scripts\allcomponents.sh;..\..\..\scripts\enterprise-numbers;..\..\..\scripts\pci.ids;..\..\..\scripts\hw.sh;..\..\..\scripts\json.sh;..\..\..\scripts\nvme.sh;..\..\..\scripts\smbios.sh;..\..\..\scripts\tcg_ccr.sh" />
	  <PaccorScriptsWindows Include="..\..\..\scripts\windows\allcomponents.ps1;..\..\..\scripts\windows\hw.ps1;..\..\..\scripts\windows\json.ps1;..\..\..\scripts\windows\nvme.ps1;..\..\..\scripts\windows\SMBios.ps1;..\..\..\scripts\windows\tcg_ccr.ps1" />
    </ItemGroup>
    <Copy SourceFiles="@(PaccorScriptsLinux)" DestinationFolder="$(ProjectDir)scripts" />
	<Copy SourceFiles="@(PaccorScriptsWindows)" DestinationFolder="$(ProjectDir)scripts/windows" />
	<ItemGroup> 
      <Content Include="resources\**"> 
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>Always</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content> 
      <Content Include="scripts\**"> 
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>Always</CopyToPublishDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content> 
	</ItemGroup>
  </Target>

  <ItemGroup>
    <PackageReference Include="paccor.HardwareManifestPlugin" Version="2.1.0" />
    <!--Source Link -->
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.103" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <!--Package resources -->
    <None Include="..\..\..\LICENSE.md" Pack="true" PackagePath="LICENSE.md" />
    <None Include="..\..\..\images\paccorpluginslogoicon.png" Pack="true" PackagePath="icon.png" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
