<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>NSA Cybersecurity Directorate</Authors>
    <PackageId>paccor.HardwareManifestPlugin</PackageId>
    <Description>Interface for paccor hardware manifest plugins. A plugin collects component identifiers for TCG Platform Certificates and can return component evidence.</Description>
    <PackageVersion>2.2.0</PackageVersion>
    <PackageTags>paccor;platform;certificate;hardware;manifest;interface</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <!--Source Link github.com/dotnet/sourcelink -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.2" />
    <PackageReference Include="Grpc.Tools" Version="2.84.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PlatformCertificate.Proto" Version="2.2.0" />
    <PackageReference Include="PlatformCertificate.Proto.ProtoFiles" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Resources\HardwareManifest.proto" ProtoRoot="Resources" GrpcServices="None" AdditionalImportDirs="$(PlatformCertificateProtoFilesDir)" />
  </ItemGroup>

  <ItemGroup>
    <!--Package resources -->
    <None Include="..\..\..\LICENSE.md" Pack="true" PackagePath="LICENSE.md" />
    <None Include="..\..\..\images\paccorpluginslogoicon.png" Pack="true" PackagePath="icon.png" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
