package paccor.tcg.credential;

import org.bouncycastle.asn1.DERUTF8String;

public class PEMCertStringTraitTest {
    public static final String PEM_CERT_STRING_1_TRAIT_DESC = "PEM Cert String Trait Test 1";
    public static final String PEM_CERT_STRING_1 = """
-----BEGIN CERTIFICATE-----
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTVENDQWpHZ0F3SUJBZ0lVQ2VTS1d3MEFp
VmNBMGkxbzNDQ3JZVW94VmxRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05ERUxNQWtHQTFVRUJoTUNW
Vk14RkRBU0JnTlZCQW9NQzJWNFlXMXdiR1V1WTI5dE1ROHdEUVlEVlFRTApEQVpRUTFSbGMzUXdI
aGNOTWpVd09UQTVNVFF5TnpJNFdoY05NelV3T1RBNU1UUXlOekk0V2pBME1Rc3dDUVlEClZRUUdF
d0pWVXpFVU1CSUdBMVVFQ2d3TFpYaGhiWEJzWlM1amIyMHhEekFOQmdOVkJBc01CbEJEVkdWemRE
Q0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOREtkR1M2TVI5bisx
Y0o2dm94Vmg5QQp3SElhTXh4UDd2dmcxVCtPVi9rV1FtNjFpc0ZKeU02bEhkdzJST3hNdTRRQ3RK
OU1KdlNLZ2JRQTl6R1ViR0RxCk5YVWJwU0Vzc3orelFqMzNVTjR0TGdTWU82MGtpa3h0RnZjam8v
eGFGZGUrTDlGZnA3b1lUSWRTRmV0MmxZTUkKcU9iTzZ5NHBURGZtTTlxbXBhdUlHRndXK0RCRy8v
Yml5eER3M3BDK2pHS1BVeW00SUpjbnhNM0pKRndEczBJWQpCTFk5cmVHNkwvN0ZCbVhPMGtnNy83
bUIrZjZVVHdUT2JOVFhNcUpzaHZRWVoxNUwwTGxrVmlnV3VVNDdBRTJVClNtbk9DMW5PR0YvREsr
V2RYUXVvRXNmS0ZqYlRPYWJEZnQyakxTVytRK0l3b29kaWdqMjkvNmtUZlBCM2N6TUMKQXdFQUFh
TlRNRkV3SFFZRFZSME9CQllFRkt0NG1hVmlpeFpaZ05HcC9USFl5Rkprc2c0d01COEdBMVVkSXdR
WQpNQmFBRkt0NG1hVmlpeFpaZ05HcC9USFl5Rkprc2c0d01BOEdBMVVkRXdFQi93UUZNQU1CQWY4
d0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnRUJBR1RlUHgwU3Q2VjMyQkhNTEFmazlXYjB0RjVrQk90
WmJWek4vSXhjYnFIL0hmdGwKcHJPR0d2QVd5R2ZvS3FnM0d1VG55MXRTdWRPNFVtSlFFc2FSK0V3
V1p2QTV0Tm1XUys1ZUc3MW9nY1FwaWQycApwMDNQMk9pdDEvR25Zdy9HN0dacW50RjFCdDltK2pt
UlpCMFpCQkdabHQ5UXpIZTEwYit5WE9QOEpUWFpudUpYCktOek5ZTHR5Qm02RWZxRERVakFadk1j
WGNVNTN2Vmh1d3ByQWdDaXRVTGhvZjd4NGZGalJSc3hidFI1R2M1TjQKUjkvby9jbkJPVkFWM1lm
MW8zY2h6TXZPL1RUbWlVKzJzcnJ4TnVFcWoraWpYOHNLOUVSUlgvb1oyR0NuZzRTSAppTzRXcVlW
czlJczJWOGpNT2JacGFSNGNCTFZMQlltVGZwL1VTR0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
LS0K
-----END CERTIFICATE-----
""";

    /**
     * If any aspect of this Trait is altered, verify its usage in other tests.
     * @return A test PEMCertStringTrait
     */
    public static final PEMCertStringTrait samplePEMCertStringTrait1() {
        return PEMCertStringTrait.builder()
                .traitRegistry(TCGObjectIdentifier.tcgTrRegNone)
                .description(new DERUTF8String(PEMCertStringTraitTest.PEM_CERT_STRING_1_TRAIT_DESC))
                .traitValue(new DERUTF8String(PEMCertStringTraitTest.PEM_CERT_STRING_1))
                .build();
    }
}
