name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: dotnet/paccor_scripts
      run: dotnet restore
    - name: Build
      working-directory: dotnet/paccor_scripts
      run: dotnet build
    - name: Test
      working-directory: dotnet/paccor_scripts
      run: dotnet test
    - name: Pack
      working-directory: dotnet/paccor_scripts
      run: dotnet pack
    - name: Publish
      working-directory: dotnet/paccor_scripts/paccor_scripts
      run: |
        dotnet -r linux-x64 -c Release
        dotnet -r win-x64 -c Release