name: .NET build HardwareManifest

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      working-directory: dotnet/HardwareManifestPlugin
      run: dotnet restore
    - name: Build
      working-directory: dotnet/HardwareManifestPlugin
      run: dotnet build
    - name: Test
      working-directory: dotnet/HardwareManifestPlugin
      run: dotnet test
    - name: Pack
      working-directory: dotnet/HardwareManifestPlugin
      run: dotnet pack
    - name: Nuget SHA256
      shell: bash
      run: |
        sha256sum dotnet/HardwareManifestPlugin/**/bin/Release/*nupkg
        ls -go --full-time dotnet/HardwareManifestPlugin/**/bin/Release/*nupkg
    - name: Nuget Packages
      if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'v') || contains(github.event.head_commit.message, '[save artifacts]') || contains(github.event.head_commit.message, '[save hardwaremanifest artifacts]')
      uses: actions/upload-artifact@v7
      with:
        name: nuget.rc.builton_${{ matrix.os }}
        retention-days: 1
        if-no-files-found: error
        path: |
          dotnet/HardwareManifestPlugin/**/bin/Release/*nupkg
